'use client'

import { useState, type FormEvent } from 'react'
import { useApp } from '@/components/app-provider'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Icon } from '@/components/ui/icon'
import { PageHeader } from '@/components/ui/page-header'
import { initials } from '@/domain/format'

export default function CatalogsPage() {
  const { snapshot, busy, addProject, addVehicle, inviteEngineer } = useApp()
  const [message, setMessage] = useState<string>()

  async function projectSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await addProject(String(data.get('code')), String(data.get('name'))); event.currentTarget.reset(); setMessage('Proyecto agregado.') } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Error al agregar proyecto.') } }
  async function vehicleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await addVehicle(String(data.get('plate')), String(data.get('name')), String(data.get('deviceId'))); event.currentTarget.reset(); setMessage('Vehículo agregado.') } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Error al agregar vehículo.') } }
  async function engineerSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await inviteEngineer(String(data.get('fullName')), String(data.get('email'))); event.currentTarget.reset(); setMessage('Ingeniero agregado o invitado.') } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Error al invitar ingeniero.') } }

  return <><PageHeader description="Administra proyectos, vehículos e ingenieros para programar, asignar y reportar los recorridos." eyebrow="Administración" title="Equipo y unidades"/>{message ? <div className="notice" role="status"><Icon name="check"/><div><strong>Actualización</strong><span>{message}</span></div></div> : null}<div className="catalog-grid" style={{ marginTop: 16 }}><Card title="Proyectos" subtitle={`${snapshot.projects.length} registros`}><form onSubmit={projectSubmit}><div className="form-grid" style={{ gridTemplateColumns: '120px 1fr' }}><label>Código<input name="code" placeholder="PRY-001" required/></label><label>Nombre<input name="name" placeholder="Proyecto" required/></label></div><div className="form-actions"><Button disabled={busy} type="submit" variant="secondary">Agregar proyecto</Button></div></form><div className="catalog-list">{snapshot.projects.map((project) => <div className="catalog-item" key={project.id}><span className="avatar">{project.code.slice(-2)}</span><div><strong>{project.code}</strong><small>{project.name}</small></div></div>)}</div></Card><Card title="Vehículos" subtitle={`${snapshot.vehicles.length} unidades`}><form onSubmit={vehicleSubmit}><div className="form-grid"><label>Placa<input name="plate" placeholder="ABC-123-A" required/></label><label>Nombre<input name="name" placeholder="Unidad GBS-01" required/></label><label className="form-grid__wide">ID de la plataforma GPS<input name="deviceId" placeholder="Se completa al conectar la plataforma"/></label></div><div className="form-actions"><Button disabled={busy} type="submit" variant="secondary">Agregar vehículo</Button></div></form><div className="catalog-list">{snapshot.vehicles.map((vehicle) => <div className="catalog-item" key={vehicle.id}><span className="trip-card__icon"><Icon name="car"/></span><div><strong>{vehicle.plate} · {vehicle.name}</strong><small>{vehicle.locateliaDeviceId ?? 'Sin ID de plataforma GPS'}</small></div></div>)}</div></Card><Card title="Ingenieros" subtitle="Acceso limitado a sus viajes"><form onSubmit={engineerSubmit}><div className="form-grid"><label>Nombre<input name="fullName" placeholder="Nombre completo" required/></label><label>Correo<input name="email" placeholder="correo@gbs.com" required type="email"/></label></div><div className="form-actions"><Button disabled={busy} type="submit" variant="secondary">Invitar ingeniero</Button></div></form><div className="catalog-list">{snapshot.profiles.filter((profile) => profile.role === 'engineer').map((profile) => <div className="catalog-item" key={profile.id}><span className="avatar">{initials(profile.fullName)}</span><div><strong>{profile.fullName}</strong><small>{profile.email}</small></div></div>)}</div></Card></div></>
}
